### ISSUE TITLE
Delete it

### ISSUE THREAD

**Issue by RealGranfill** [robertkirkman/omm-coop#1]
owokitty, Issac wants this to be deleted immediately for the following reasons:

1. Peachypeach doesn't want anyone to do this and you must respect her wishes
2. OMM rebirth is coming so that people can get omm legally in a better experience

Either way, DELETE IT NOW.

**Comment by CosmicNyan** [comment]
owokitty doesn't even have the right to upload this it isn't his mod

**Comment by robertkirkman** [comment]
You are **not** the "original author" of anything here. It is a well-established fact that Mario is the property of Nintendo Corporation, and therefore anything involving Mario is also the property of Nintendo, regardless of whether it is an officially licensed Nintendo product, and only Nintendo has the authority to copy strike it.

That is why you have not been able to take down this repository - **you don't own it or have the authority to issue copy strikes on behalf of Nintendo.**

_It would appear_ that Nintendo has, so far, for whatever reason, not determined it necessary to copy strike this repository themselves, despite its blatant plagiarism of the Nintendo products Super Mario 64 and Super Mario Odyssey, so **it will remain available until such time as that happens.**

Below are excerpts from Nintendo's official statements insofar as they directly pertain to this subject. In particular, I would like to call attention to Nintendo's well-known opinion that **infringement begins at the moment the first copy is made, as opposed to the moment the copy is first redistributed**, which these statements reflect.


>[!IMPORTANT]
>### Nintendo of America
>
>"**Is It Okay to Copy or Download Older Titles That Are No Longer Sold?**"
>
>"No, the current availability of a game in stores is irrelevant as to its copyright status. Copyrights do not enter the public domain just because they are no longer commercially exploited or widely available. Therefore, the copyrights of games are valid even if the games are not found on store shelves, and using, copying and/or distributing those games is a copyright infringement."
>
>"While we recognize the passion that players have for classic games, supporting emulation also supports the illegal piracy of our products."
>
>"**But can’t I make a backup copy if I own the video game?**"
>
>"You may be thinking of the backup/archival exception under the U.S. Copyright Act. There is some misinformation on the Internet regarding this backup/archival exception. This is a very narrow limitation that extends to computer software. Video games are comprised of numerous types of copyrighted works and should not be categorized as software only. Therefore, provisions that pertain to backup copies would not apply to copyrighted video game works..."
>
>### Nintendo of Australia
>
>"**Game copiers**"
>
>"Game copiers are products which connect to a computer and enable users to illegally copy video game software onto any type of memory cartridge, disk or directly to the hard drive of a personal computer."
>
>"Game copiers circumvent the technological protection measures in Nintendo products and enable the user to make, play and distribute illegal copies of Nintendo video games which infringe Nintendo's intellectual property. These devices allow for the uploading and downloading of Nintendo game data or so called Read Only Memory (ROMs) to and from the Internet."
>
>"**Are game copying devices illegal?**"
>
>"Yes. **Game copiers that are used to copy video game software without authorization onto any type of memory device or the hard drive of a personal computer are illegal.** They infringe copyright in computer programs in Nintendo products and infringe Nintendo trade marks. They are also circumvention devices. The manufacturing, importing or distributing of circumvention devices is prohibited under the Copyright Act"

As you can see, in the opinion of Nintendo themselves, the "Odyssey's Mario Moveset" mod for the "Super Mario 64 Ex Coop" fork of the "Super Mario 64 decompilation project" is an **"illegal" project** specifically because its use **_requires_ the use of an "illegal" "game copier" to "copy video game software onto the hard drive of a personal computer"**. 

That is not the only criterion that Nintendo uses when considering whether to copy strike a project, either, and in a great many cases it has not been used as the sole criterion. Nintendo has repeatedly and successfully demonstrated their de jure and de facto authority and ability to C&D, copy strike, seize or otherwise take down an ever-expanding number of cases of plagiarism that are, in their opinion, illegal, regardless of the exact mechanisms by which Nintendo-related content is involved in each case.

There is no single set of criteria that "Odyssey's Mario Moveset" could be said to meet, that is not also met by one or more of the many projects that Nintendo has taken action to remove. **It is therefore obvious that if any entity could be said to have de facto or de jure total authority over the copying and distribution of the "Odyssey's Mario Moveset" project, it is Nintendo, not you.**

References:
https://www.nintendo.com/au/legal/nintendo-intellectual-property/
https://en-americas-support.nintendo.com/app/answers/detail/a_id/55888/~/intellectual-property-%26-piracy-faq
https://www.romanolaw.com/ninten-dont-breaking-down-the-yuzu-emulator-lawsuit/
https://gamerant.com/pokemon-vs-palworld-lawsuit-controversy-explained/
https://arstechnica.com/civis/threads/switch-emulator-ryujinx-shuts-down-development-after-%E2%80%9Ccontact-by-nintendo%E2%80%9D.1503281/
https://gbatemp.net/threads/nintendo-reportedly-issues-dmca-takedown-for-switch-homebrew-projects-skyline-switch-emulator-development-ceased.632406/
https://dolphin-emu.org/blog/2023/07/20/what-happened-to-dolphin-on-steam/
https://gbatemp.net/threads/gitlab-has-taken-down-the-suyu-nintendo-switch-emulator.651543/
https://arstechnica.com/gaming/2024/02/after-14-5m-judgments-console-hacker-paid-nintendo-25-a-month-from-prison/
https://www.nintendolife.com/news/2020/10/nintendo_lawyers_hit_fan-made_zelda_game_with_fatal_copyright_claim
https://www.pcgamesn.com/super-mario-64/super-mario-64-online-romhack-dmca
https://www.nintendolife.com/news/2016/08/nintendo_issues_takedown_notices_for_impressive_fan-made_metroid_ii_remake_am2r
https://gbatemp.net/threads/nintendo-shuts-down-pokemon-prism-rom-hack.453935/
https://www.pcgamer.com/pokemon-uranium-interview/
https://www.nintendolife.com/news/2021/08/the_fan-made_2d_metroid_prime_game_has_been_forced_to_shut_down
https://www.engadget.com/garrys-mod-faces-deluge-of-nintendo-related-dmca-takedown-notices-123027589.html
https://gamingreinvented.com/news/nintendo-takes-down-botw-mod-second-wind-videos/
https://www.gonintendo.com/stories/257590-nintendo-completely-kills-off-full-screen-mario-project
https://gamingreinvented.com/feature/nintendo-shuts-down-the-legend-of-zelda-ocarina-of-time-2d/
https://www.eurogamer.net/nintendo-issues-takedown-notice-for-super-mario-64-hd-project
https://www.gamesradar.com/after-almost-10-years-unofficial-pokemon-website-known-for-sharing-fan-made-games-shuts-down-after-reportedly-receiving-a-dmca-takedown-notice/
https://www.engadget.com/2010-04-02-nintendo-shuts-down-fan-made-pokemon-mmo.html
https://gamerant.com/nintendo-removes-hundreds-fan-games-dmca-takedown-game-jolt/
https://www.engadget.com/2016-04-08-nintendo-kills-3d-zelda-tribute-game-on-the-web.html
https://www.vg247.com/nintendo-smash-bros-melee-free-melee-fans-tournament-hashtag
https://www.stuff.co.nz/entertainment/games/83987415/nintendo-shuts-down-parody-game-no-marios-sky
https://www.pcgamer.com/software/nintendo-3ds-emulator-citra-taken-offline-as-collateral-damage-in-yuzu-settlement/
https://news.itsfoss.com/nintendo-youtube-takedown/
